import BasePage from './components/BasePage';

const rows = [
  {
    key: '1',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '2',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '3',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '4',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '5',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '6',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '7',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '8',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '9',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
  {
    key: '10',
    datasetName: 'Dataset Name',
    description: 'description',
    resolution: '10 km',
    startTime: '25/08/2024',
    endTime: '25/08/2024',
    isAvailable: 'true',
    frequency: '1 day',
  },
];

export default function DataSourcesPage() {
  return <BasePage rows={rows} />;
}

// {
//   key: '1',
//   datasetName: faker.lorem.words(),
//   description: faker.lorem.sentence(),
//   resolution: faker.number.int() + 'km',
//   startTime: faker.date.past(),
//   endTime: faker.date.past(),
//   isAvailable: faker.datatype.boolean(),
//   frequency: '1 day',
// },
