import BasePage from './components/BasePage';

const rows = [
  {
    key: '1',
    type: 'Raster',
    title: 'Elevation Data',
    name: 'Elevation_01',
    store: 'GeoStore1',
    enabled: 'True',
    nativeSRS: 'EPSG:4326',
  },
  {
    key: '2',
    type: 'Vector',
    title: 'Road Network',
    name: 'Roads_2023',
    store: 'GeoStore2',
    enabled: 'True',
    nativeSRS: 'EPSG:3857',
  },
  {
    key: '3',
    type: 'Raster',
    title: 'Land Cover',
    name: 'LandCover_2022',
    store: 'GeoStore1',
    enabled: 'False',
    nativeSRS: 'EPSG:32633',
  },
  {
    key: '4',
    type: 'Vector',
    title: 'Administrative Boundaries',
    name: 'Admin_Bounds',
    store: 'GeoStore3',
    enabled: 'True',
    nativeSRS: 'EPSG:4326',
  },
  {
    key: '5',
    type: 'Raster',
    title: 'Climate Data',
    name: 'Climate_2021',
    store: 'GeoStore4',
    enabled: 'True',
    nativeSRS: 'EPSG:3857',
  },
  {
    key: '6',
    type: 'Vector',
    title: 'Hydrology',
    name: 'Rivers_Lakes',
    store: 'GeoStore5',
    enabled: 'False',
    nativeSRS: 'EPSG:32633',
  },
  {
    key: '7',
    type: 'Raster',
    title: 'Soil Moisture',
    name: 'SoilMoisture_2020',
    store: 'GeoStore2',
    enabled: 'True',
    nativeSRS: 'EPSG:4326',
  },
  {
    key: '8',
    type: 'Vector',
    title: 'Land Use',
    name: 'LandUse_2023',
    store: 'GeoStore3',
    enabled: 'True',
    nativeSRS: 'EPSG:3857',
  },
  {
    key: '9',
    type: 'Raster',
    title: 'Temperature Anomalies',
    name: 'Temp_Anomalies_2019',
    store: 'GeoStore4',
    enabled: 'True',
    nativeSRS: 'EPSG:32633',
  },
  {
    key: '10',
    type: 'Vector',
    title: 'Population Density',
    name: 'PopDensity_2022',
    store: 'GeoStore1',
    enabled: 'True',
    nativeSRS: 'EPSG:4326',
  },
];

export default function DataSourcesPage() {
  return <BasePage rows={rows} />;
}
